version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: momos
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mysql", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: mysql
      DB_PASSWORD: password
      DB_DATABASE: momos
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  load-test:
    image: grafana/k6
    volumes:
      - ./k6-scripts:/scripts
    entrypoint: ["k6", "run", "/scripts/script.js"]
    depends_on:
      app:
        condition: service_healthy
    networks:
      - default

volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local

networks:
  default:
    driver: bridge